version: '3.0'
services:
  mysql8:
    image: 'mysql:8.0.29'
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      # 初始化脚本
      - ./script/mysql/:/docker-entrypoint-initdb.d/
    ports:
      - "13306:3306"
  redis:
    image: 'bitnami/redis:7.2.4'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '16379:6379'