apiVersion: v1
kind: PersistentVolumeClaim
metadata:
# mysql要用的东西
  name: webook-mysql-claim
spec:
# 这里随便取名
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi